
tasks:
  
  - name: venuzia

    before: |

      echo "🚀"

    init: |
      
      # ------------------------------------
      # Install Venusia
      # ------------------------------------

      wget https://github.com/bots-garden/procyon/releases/download/0.0.5/alcor-0.0.5-linux-amd64.tar.gz
      mkdir venusia
      tar -zxf venusia-0.0.5-linux-amd64.tar.gz --directory venusia
      
      mkdir venusia/functions

      # ------------------------------------
      # Install Mkcert to generate
      # self-signed certificates
      # ------------------------------------

      sudo apt install libnss3-tools -y
      wget https://github.com/FiloSottile/mkcert/releases/download/v1.4.3/mkcert-v1.4.3-linux-arm64
      sudo cp mkcert-v1.4.3-linux-arm64 /usr/local/bin/mkcert
      sudo chmod +x /usr/local/bin/mkcert

      cd venusia
      mkcert -install
      mkcert venusia.local localhost 127.0.0.1 ::1
      cp venusia.local+3-key.pem venusia.local.key
      cp venusia.local+3.pem venusia.local.crt
      rm *.pem

      # ------------------------------------
      # Start Venusia
      # ------------------------------------

      REGISTRY_CRT="venusia.local.crt" \
      REGISTRY_KEY="venusia.local.key" \
      REGISTRY_HTTP=9999 \
      ./venusia

  - name: procyon
    
    init: |

      # ------------------------------------
      # Install Venusia
      # ------------------------------------

      wget https://github.com/bots-garden/procyon/releases/download/0.0.5/procyon-0.0.5-linux-amd64.tar.gz
      mkdir procyon
      tar -zxf procyon-0.0.5-linux-amd64.tar.gz --directory procyon

      mkdir procyon/executors

      # ------------------------------------
      # Install sat
      # ------------------------------------
      git clone https://github.com/suborbital/sat.git
      cd sat
      make sat
      cp .bin/sat ..procyon/executors
      cd ..
      rm -rf sat

      # ------------------------------------
      # Start Procyon
      # ------------------------------------
      cd procyon
      ./procyon

  - name: alcor

    init: |

      wget https://github.com/bots-garden/procyon/releases/download/0.0.5/venusia-0.0.5-linux-amd64.tar.gz
      mkdir alcor
      tar -zxf alcor-0.0.5-linux-amd64.tar.gz --directory alcor
      rm alcor-0.0.5-linux-amd64.tar.gz 

      # ------------------------------------
      # Start Alcor
      # ------------------------------------
      cd alcor
      ./alcor

  - name: subo

    init: |

      # ------------------------------------
      # Install the Suborbital CLI
      # ------------------------------------
    
      brew tap suborbital/subo && \
      brew install subo



ports:
    # Alcor reverse proxy 
  - port: 8080
    visibility: public
    # Procyon
  - port: 9090
    visibility: public
    # Venusia Registry
  - port: 9999
    visibility: public

vscode:
  extensions:
    - wayou.vscode-todo-highlight
    - pkief.material-icon-theme
    - golang.go
    - grain-lang.vscode-grain
    - rust-lang.rust

